Add scheduling checks to ajax scheduler
learning-unlimited/ESP-Website pull request #3235
Opened 2021-03-06 19:29 UTC by willgearty

This adds a set of scheduling checks to the ajax scheduler that can be enabled by selecting them in the new options tab (only one can be enabled at a time):
![image](https://user-images.githubusercontent.com/7232514/110218295-907ca900-7e7e-11eb-83b0-c3e94fb30a0d.png)

Once a scheduling check is enabled, it will be used to color the cells in the scheduling matrix. For example, for the "Double-Booked Teachers" check, it will color sections red that overlap in time and have the same teacher(s):
![image](https://user-images.githubusercontent.com/7232514/110218305-b013d180-7e7e-11eb-9728-aa419e821c09.png)

This functionality works for looking at sections that are already scheduled and for scheduling sections in new spots (e.g. if the capacity check is enabled, the color of the cell will change as you move your cursor over different cells in the matrix based on the capacities of the classrooms). This means that in addition to using these checks AFTER scheduling, you can also use them DURING scheduling to see if adding/moving a section in a particular spot will cause or remove an issue (e.g. will make a teacher "hungry" or have to "run"). You can see this in this example screenshot where I am moving the B6s1 section:
![image](https://user-images.githubusercontent.com/7232514/110218520-d423e280-7e7f-11eb-94f5-cad736b98441.png)

Then, once a section is scheduled, we update the colors of ALL cells to indicate if new issues have arisen. Note: I'm not sure how the performance is for this last part for larger programs, but I imagine it shouldn't be too bad since javascript is pretty efficient, and it's not like it will prevent you from scheduling other sections.

Fixes https://github.com/learning-unlimited/ESP-Website/issues/1406.

2021-03-11 02:33 UTC, kkbrum requested changes
Really cool feature addition.

Not sure what's going on, but for both the "running teachers" and "double-booked teachers", one of my classes turns black and is no longer clickable: 

![image](https://user-images.githubusercontent.com/25392075/110726674-d079be00-81e7-11eb-8db6-943d4c353e1b.png)

2021-03-11 02:33 UTC, kkbrum commented on esp/public/media/scripts/ajaxschedulingmodule/ESP/Cell.js
> +                // Count how many teachers are teaching other sections at the same time as this one
is this referring to coteachers of a class? I think that could be more clear if so.

2021-03-11 02:33 UTC, kkbrum commented on esp/public/media/scripts/ajaxschedulingmodule/ESP/Cell.js
> +                // Count how many teachers are teaching other sections immediately before or after this one in a different room
ditto

2021-03-11 02:53 UTC, willgearty commented
Can you take a screenshot of the console log when that happens @kkbrum?

2021-03-18 01:21 UTC, kkbrum approved these changes
A little hard to test with my limited classes, but it looks good and I'm excited to see it in action!

2021-03-18 01:22 UTC, merged