Show options for tags that hide form fields
learning-unlimited/ESP-Website pull request #3370
Opened 2021-07-02 15:06 UTC by willgearty

This shows all of the fields that could be hidden for each form for the tags that let admins hide the fields, hopefully making it much easier for these tags to be used:

![image](https://user-images.githubusercontent.com/7232514/124294088-51591e80-db25-11eb-9477-88b466708978.png)

Fixes https://github.com/learning-unlimited/ESP-Website/issues/3358 and fixes https://github.com/learning-unlimited/ESP-Website/issues/3357.

2021-07-07 01:06 UTC, kkbrum commented
So this looks great, and technically functions perfectly. But:

1) it allows admins to set themselves up for failure. You can remove important fields such as "title" or "duration" or "number of sections" from teacher reg, but then when you try to register a class, you'll never be able to succeed: 

![image](https://user-images.githubusercontent.com/25392075/124684009-493e0d80-de9c-11eb-9244-bb1d45a83f53.png)

Thus we should filter out the required fields from the dropdowns. 

2) Perhaps we want to display the label of the field names, ie "Maximum Number of Students" instead of "class_size_max". Right now it looks like most of the coded field names are self-explanatory, but it may not be the most user friendly in the future. But the labels may also be too long to be pretty in a dropdown. Additionally, you can override the label for some of the fields which may be a bit weird, but I think we would just display the current label (that may get changed when you hit submit on the tags page). Up to you if you want to just leave the coded field names as is, or try to make it a bit friendlier.

2021-07-12 16:48 UTC, willgearty commented
OK, now we only show fields that are NOT required (e.g., this results in only 6 field options for the teacher reg form tag). I also changed the labels for the teacher reg form tag to the labels used in the form, but we don't have built-in labels for the profile form fields (we specify the labels in the templates instead), so I kept the field names for those tags.

2021-07-14 01:30 UTC, kkbrum requested changes
This looks good for teacherreg. Can we do the same thing with using label text instead of the code names for the drop downs for volunteer/guardian/student/educator profiles?

Additionally, this might be for another PR, but it seems like we can deprecate a bunch of tags due to this hide feature. For example, there are tags asking about whether to include shirt size, shirt type, gender fields in various profiles, which are now redundant to the hide fields tag. I'm a fan of getting rid of all these extra tags now.

2021-07-14 15:07 UTC, willgearty commented
@kkbrum For the profile forms, we don't actually have labels defined for any of the fields. We just put labels in the templates for the profiles.

I'll look into which tags can be deprecated.

2021-07-14 15:12 UTC, willgearty commented
OK, so the tags you are referring to actually SHOW those fields (they are hidden by default). If you want to get rid of those tags, we'd either need to

1. Make them the default values for this tag or
2. Make them not hidden by default

2021-07-16 00:07 UTC, kkbrum commented
Okay that's fine about the labeling. I have some more thoughts about the shirt/gender tags that I'm going to put in a new PR.

2021-07-16 00:07 UTC, kkbrum approved these changes

2021-07-16 00:08 UTC, merged