Add scheduler support for timeslots of any length
learning-unlimited/ESP-Website pull request #3381
Opened 2021-07-22 15:29 UTC by willgearty

Previously, parts of the ajax scheduler code assumed timeslots were once per hour, never longer than an hour, and always the same length across a program. This removes those assumptions and allows for timeslots of any length (possibly varying across a program) and any number per hour.

Given that this now supports timeslots that may be longer than the scheduled classes (e.g., you can now schedule a 2 hour class across two 1.5 hour timeslots, which would result in a large time gap between the end of the class and the end of the second timeslot), this puts a little extra responsibility on the admins that are scheduling the classes. To hopefully help with this, the "length" on the hover and infopanel tooltips is now shown as "X hours and Y minutes".

Fixes #2705.

2021-07-23 01:21 UTC, kkbrum requested changes
Hm well the scheduler and I don't get along very well, but I'm having some undesired behavior.

It's (sometimes?) allowing me to schedule longer classes in fewer timeslots than should be allowed:

![image](https://user-images.githubusercontent.com/25392075/126727367-e32a3240-5efa-4baa-b5c8-234829083a56.png)

or even worse:

![image](https://user-images.githubusercontent.com/25392075/126727389-473c8c25-f464-4787-815f-ac0e25f2e9b0.png)

2021-07-24 16:26 UTC, willgearty commented
OK, I believe that should be the last of the code that makes horrendous assumptions about timeslot lengths/times. Please try to break it again!

2021-07-25 17:17 UTC, hwatheod commented
I guess this isn't the place to address this issue, but how do we ever end up with a non-integer number of minutes for a class length?  No one schedules class times at a sub-minute level. If we are storing class durations as fractional hours, perhaps we should store all class durations as an integer number of minutes instead.

2021-07-26 00:26 UTC, willgearty commented
> I guess this isn't the place to address this issue, but how do we ever end up with a non-integer number of minutes for a class length? No one schedules class times at a sub-minute level. If we are storing class durations as fractional hours, perhaps we should store all class durations as an integer number of minutes instead.

Yeah, the problem stems from trying to store all durations as fractions of hours (as a `DecimalField` with only 2 digits), then converting back to minutes. We've had to deal with this rounding issue several times now (#2771, #2704, #2668), and the solution to now has basically been to always round things the same way for other time-based parts of the website. My most recent commit rounds the times to a whole number of minutes (at least visually), and I didn't notice any actual rounding issues when comparing the fit of classes to timeslots (at least with the specific example @kkbrum demonstrated here).

It's not a bad idea to store duration as an integer of minutes...Although it would certainly take a lot of work to make sure everything is updated appropriately across the codebase.

2021-07-28 00:37 UTC, kkbrum requested changes
This mostly looks great. But I do have an issue where I can't put a 34 minute class into a 34 minute timeslot. Presumably another rounding issue? But I'm able to put a 17 minute class into a 17 minute timeslot...

![image](https://user-images.githubusercontent.com/25392075/127245034-70c8001f-a9c8-4c7c-97fe-c0ac5d1bca9e.png)

2021-07-28 01:02 UTC, kkbrum approved these changes
Woohoo!

2021-07-28 01:02 UTC, merged