Swap sections in the ajax scheduler
learning-unlimited/ESP-Website pull request #3487
Opened 2022-02-20 17:45 UTC by willgearty

This allows you to swap two sections in the ajax scheduler by selecting one and then holding CTRL/CMD and clicking on the other one. If one is longer than the other, it will attempt to swap any other sections necessary to perform the full swap (after a confirmation is provided from the user). If the swap is not possible (due to teacher availability or temporal fitting), an error message is provided.

The swapping appears to work very cleanly for almost all cases (e.g., same room, same times, different lengths, etc.) EXCEPT when you try to swap a single section with multiple sections that partially overlap in time. I'm not sure what the issue is, but I have a hunch it has to do with availability caching, but I'm going to wait until this has been reviewed to see if there are any other edge cases that need to be fixed. Also, sometimes the sections are unscheduled after swapping, but they should always be rescheduled automatically once the site double-checks the change log (every 5 seconds).

In hindsight, I'm wondering if I maybe should have performed the swap as a single back-end action, instead of as 3 discrete actions (unschedule, reschedule, schedule). If the issues described above persist, I might need to change to this behavior instead.

I also fixed a bug that prevented scheduled sections from being rescheduled to an overlapping time (e.g., from 10-12 to 9-11) even if there was the proper availability.

Fixes https://github.com/learning-unlimited/ESP-Website/issues/1405.

2022-03-09 01:43 UTC, kkbrum requested changes
Can you add a note about the swap feature to the upper right hand info box on the scheduler? I think the slight lag to the unschedule & rescheduling process is fine, but I would include a note about it in the info box as well. Like "note: this will take a few seconds to complete the action" just so people know it's not behaving weirdly.

The behavior of checking the "override availability" box is a bit weird to me with this. I'm not really sure what it's doing; sometimes it says it can't swap the classes, sometimes it unschedules one of the classes. I believe that if the reason the classes cannot be swapped is teacher availability of one of the classes, the override button should allow the swap.

2022-03-09 01:43 UTC, kkbrum commented on esp/public/media/scripts/ajaxschedulingmodule/ESP/Sections.js
> +                        this.matrix.messagePanel.addMessage("Error: can not swap those classes.", color = "red");
It would be more helpful to give an indication as to why the classes can not be swapped

2022-03-13 21:44 UTC, willgearty commented
Random thought: are there repercussions of unscheduling one set of the classes? (student/teacher registration-wise)

2022-03-16 00:18 UTC, kkbrum commented
Idea: Why not have it so that if you click an unscheduled class from the class list, you can replace a scheduled class with it by doing ctrl click? Seems like this is a logical extension and would make scheduling even faster

2022-03-16 00:25 UTC, kkbrum commented
The more seamless swapping looks great! And I have not found any more weirdness with overriding availabilities.

2022-03-23 00:33 UTC, willgearty commented
That should be everything, @kkbrum!

2022-03-25 00:20 UTC, kkbrum approved these changes
Wow this is so seamless and quick and easy! Now when you accidentally schedule section 2 before section 1, it'll be so easy to fix!!

2022-03-25 00:28 UTC, merged