Add UI for program modules
learning-unlimited/ESP-Website pull request #3510
Opened 2022-03-31 15:13 UTC by willgearty

This page lets you change the sequence and requiredness of program modules.

![image](https://user-images.githubusercontent.com/7232514/161089311-352143b0-8700-43a3-8c30-39f75bfa9ace.png)

This is the first step towards #3497.

2022-04-01 00:43 UTC, kkbrum requested changes
This looks very nice!

I know you left warnings, but I think this page currently has too much flexibility for admins to not understand what a module does and put it in a bizarre spot. 

It would probably be too hard / not flexible enough to enforce certain constraints (ie. not allowing certain modules to switch requiredness or go before/after a different module), but I'm wondering if we can add a comment when you hover over each module with some tips. Like "this should only go after __" and "this module does ___" (like the core student reg module, who knows what that means and where it should go in the order? presumably first? should it be required?). I think some constraints/tips for each module would be helpful. 

Also, in a similar vein, I'm wondering if we can add a "restore to defaults" button so that when someone inevitably changes a ton and can't get anything to work anymore, they can start over with the default sequence. Probably a default button for sequence and another one for requiredness. 

Finally, Yale uses the "program module objects" admin page to also change required labels (ie to say that credit card payment is "required by ___" even though the module is not required). So could we incorporate the required labels field into this management page? Since this is very uncommon, perhaps there could be a little button next to each module with a comment glyph that would open a field below that would allow you to change the label for that module? Just so that this rare occasion doesn't clutter the page by having the field open for each module. Then if the required label has anything in it, that field would stay visible (so admins dont forget it's there and to change it if necessary).

2022-04-22 01:36 UTC, willgearty commented
OK, how's that all look @kkbrum?

2022-04-27 00:26 UTC, kkbrum requested changes
The requirement label text boxes are too wide in fruit salad:

![image](https://user-images.githubusercontent.com/25392075/165413696-91fb0347-4624-4d2f-9ee9-bea30120f587.png)

Otherwise, everything looks great!

2022-05-04 00:23 UTC, kkbrum approved these changes

2022-05-04 13:54 UTC, merged