Db receipts
learning-unlimited/ESP-Website pull request #3521
Opened 2022-04-17 17:09 UTC by willgearty

This adds a user interface to edit the DBReceipts for a program to the program settings page:
![image](https://user-images.githubusercontent.com/7232514/163725071-ab67c48c-00d7-41e4-a711-f655ac33c429.png)

Another step towards #3497.

2022-04-20 00:53 UTC, kkbrum requested changes
The help text paragraphs are cut off on the right in fruitsalad 

![image](https://user-images.githubusercontent.com/25392075/164121897-4aed1e2b-a05e-4309-a567-12c2bf11c76a.png)


This is the error i got when trying to confirm reg when i have not yet confirmed reg (all default dbreceipts)

![image](https://user-images.githubusercontent.com/25392075/164124141-d30e1593-4ae8-4d3c-bfd9-c6f837407a57.png)

I also get an error when trying to confirm or cancel reg if i've already confirmed it, but I'm not sure if my program is just broken or if it's a real error. I cant test on another program while the above error exists though.

![image](https://user-images.githubusercontent.com/25392075/164125438-90d0197a-a67f-448b-b31b-9580f593016d.png)

2022-04-22 15:11 UTC, willgearty commented
That should fix the first two issues @kkbrum. The cancelreg should show the "cancel" receipt. Did you perhaps copy the confirmation text to the cancel receipt during testing? Also, it only actually cancels classes if this box is checked:
![image](https://user-images.githubusercontent.com/7232514/164743047-e201368e-5eb7-4380-b333-c91d4bb491e8.png)

2022-04-27 01:19 UTC, kkbrum requested changes
Could you add "registration receipts" to the list on the program management page describing what the program settings page does? It currently says: "Modify Settings for This Program: Emails, program caps and modules, class categories, and flag types"

Whether I have text in the cancel receipt or not, and whether I check the cancel classes option or not, it still redirects me to the confirm reg receipt instead of the cancel receipt or core reg...

2022-05-04 00:18 UTC, kkbrum approved these changes

2022-05-04 00:20 UTC, merged