Change extracost selections after paying
learning-unlimited/ESP-Website pull request #3592
Opened 2023-01-13 01:56 UTC by willgearty

This adds the ability (enabled by default) for students to return to the extracosts page after they have paid via credit card and choose different extracost options. This could be a 1 for 1 change (where there is no balance change), a positive change in balance (where the student would then need to pay via credit card again), or a negative change in balance (which we treat as a temporary/permanent donation).

The students can return to this page as many times as they would like between and after paying (provided the tag is enabled, which is the default). As changes are made, the (new!) subtotal (and balance if the student has paid already) at the bottom of the form updates automatically.

![image](https://user-images.githubusercontent.com/7232514/212219252-cf451125-fa0c-42cb-9c4d-e6810b34d8d0.png)

2023-01-18 01:56 UTC, kkbrum requested changes
This looks awesome! Thanks for getting all of this to work!

There is one edge case: If someone received financial aid, and then later adds an item that is covered by financial aid, the financial aid amount in the subtotal does not change. If they were given a percentage for financial aid, they will automatically receive more aid for the covered item-- this ends up reflecting correctly in the credit card form, but not in the subtotal calculated here. So I think there are two options- 1) recalculate the financial aid amount as people click on things or 2) put a little asterisk  next to the financial aid in the subtotal and then at the bottom (or the top along with the other message), add a note saying that the financial aid amount may change once different options are selected. Technically option 1 is more informative for the user (since they otherwise don't typically know which items are covered by FA and which arent), but it's obviously more tedious so I'm also fine with option 2.

Also, at least in fruitsalad, there isn't any space below the form before the end of the page-- a space would be nice. I didn't see an unclosed div anywhere causing the cut off page, but perhaps there is something lurking...

2023-01-20 15:50 UTC, willgearty commented
I've made the following changes:

- Financial aid now updates dynamically in the extra costs form
- Reordered the subtotal lines
- More help text for the line items form to try to prevent cases of financial aid covering lots of quantities of items

2023-02-03 02:03 UTC, kkbrum requested changes
This is great! One small thing: I don't love how if you have no financial aid, it removes the financial aid line heading but not the -0.00 on that line. Can we just remove the line entirely? 
![image](https://user-images.githubusercontent.com/25392075/216494602-25fafa94-bac8-48d5-80db-934e6bc3483f.png)

2023-02-08 02:03 UTC, kkbrum approved these changes
🥳 🎉 😄

2023-02-08 02:05 UTC, merged