Student schedule formatting UI
learning-unlimited/ESP-Website pull request #3627
Opened 2023-03-15 13:48 UTC by willgearty

This adds an interface to allow admins to tweak how PDF student schedules are formatted, including which components are included and the text before and after the schedule. The interface is linked to from the admin checklist (and is marked as done once the format tag exists).
![image](https://user-images.githubusercontent.com/7232514/225326605-64a8bf60-ff55-493e-b8a4-b5900f0548cf.png)

I've updated the schedule LaTeX to respect these new tag settings:
![image](https://user-images.githubusercontent.com/7232514/225327421-cd71de05-62fa-4373-aa2b-4779237738fa.png)

2023-03-17 01:26 UTC, kkbrum requested changes

2023-03-17 01:26 UTC, kkbrum commented on esp/templates/program/modules/programprintables/studentschedule.tex
> +{% for item in student.required %}\hline
This should go above the "Required choices" heading

2023-03-17 01:26 UTC, kkbrum commented on esp/esp/program/modules/handlers/programprintables.py
> +    schedule_fields = forms.MultipleChoiceField(choices = [("username", "Student's Username"),
It's forcing me to select at least one field, which I feel like shouldn't be necessary

2023-03-22 01:33 UTC, willgearty commented
Thanks @kkbrum! Your wish is my command!

2023-04-05 01:12 UTC, kkbrum approved these changes

2023-04-05 01:15 UTC, merged