Copy over choosable=2 modules from template programs
learning-unlimited/ESP-Website pull request #3640
Opened 2023-04-12 01:22 UTC by willgearty

This copies over any modules from a template program that are "choosable=2" (i.e., manually enabled). This makes it so we aren't encouraging the use of these modules, but we are copying them over in case chapters have decided to use them.

While I was at it, I also cleaned up the new program form with a pretty blue box with information about all of these seemingly random things we copy over from template programs.

Fixes https://github.com/learning-unlimited/ESP-Website/issues/3573.

2023-04-14 00:44 UTC, kkbrum requested changes
This works well and I like the new alert box. When I made the new program, although it did enable the module from the imported program, it wasn't listed on the "double check everything" page with the long list of modules right before I clicked the final magic button. It should probably be listed there? Not sure why it wasn't.

2023-04-21 14:00 UTC, willgearty commented
OK, I've gone with a new approach that modifies the newprogram/program settings javascript to keep any custom modules. Now, instead of only enabling the modules that are included via the selected questions, it is the act of checking/unchecking questions that enables/disables only those specific modules. This means that these custom modules should now be shown on the "double check everything" page.

This also fixes a bug where the "charge for items" checkbox wouldn't uncheck if your program had an admission fee.

2023-04-26 01:06 UTC, willgearty commented
I'm also adding a small change to the financial aid module which makes it hidden if there are no costs to cover. I could have made a separate PR, but it's such a small change and somewhat related to the changes already implemented here. Fixes https://github.com/learning-unlimited/ESP-Website/issues/3641.

2023-05-17 00:39 UTC, kkbrum approved these changes

2023-05-17 01:14 UTC, merged