Fix permissions in custom forms
learning-unlimited/ESP-Website pull request #3670
Opened 2023-08-04 01:40 UTC by willgearty

This fixes the lists of permissions in the custom form builder. I also fixed the text next to the checkbox so when you click the text it activates/deactivates the checkbox.

Fixes https://github.com/learning-unlimited/ESP-Website/issues/3658.

2023-08-16 00:20 UTC, kkbrum requested changes
Your changes look good, but do these restrictions actually work? It let me save the form with restricted permissions, but then if I morph into a user that does not meet the restrictions, they can still fill out the form. And, if I go back to edit the form, the permission restrictions are unselected. It either never saved, or does not pre-fill correctly, it seems.

2023-08-16 00:23 UTC, willgearty commented
I think that's outside the scope of this PR.

2023-08-16 01:26 UTC, willgearty commented
I think the permissions are only checked if you fill the form out outside of a program module (e.g., /customforms/view/[id]). I was able to trigger it and get the correct error message:
![image](https://github.com/learning-unlimited/ESP-Website/assets/7232514/ccc7e1ec-9a3c-4a01-893c-3a7de698058c)

2023-08-18 00:15 UTC, kkbrum approved these changes

2023-08-18 00:22 UTC, merged