Add and fix moderator scheduling checks
learning-unlimited/ESP-Website pull request #3678
Opened 2023-09-08 00:43 UTC by willgearty

This adds a moderator availability scheduling check to the ajax scheduler and the scheduling checks page. It also fixes the moderator title for all checks in both of these places.

I also adjusted the coloration of the cells for the teacher/moderator availability checks to be based on the proportion of teachers that are unavailable (1/1 unavailable is the same color as 5/5 unavailable, which are both much darker than 1/5 unavailable).

Note, I also fixed the tab spacing in one of the files (hence why the diff looks like I changed a lot).

Fixes #3665.

2023-09-13 00:55 UTC, kkbrum requested changes
I think this looks good so far. There is an edge case of when someone is moderating and teaching at the same time. The checks show that there is a teacher teaching when they aren't available, but the moderator check does not show an issue. I actually think neither of these should show an issue and that it should show the issue under double booked teachers (it doesnt). Perhaps we also want to add a double booked moderator check, or just include them in the double booked teacher check (my preference, i think).

2023-09-13 00:55 UTC, kkbrum commented on esp/esp/program/modules/handlers/schedulingcheckmodule.py
> +                ('mismatched_moderators', self.p.getModeratorTitle() + 's with category mismatches'),
Could you capitalize the first letter for both of these checks?

2023-09-13 00:55 UTC, kkbrum commented on esp/templates/program/modules/ajaxschedulingmodule/ajax_scheduling.html
>                          <input type="radio" name="scheduling-checks" value="mod_cats" id="scheduling-checks-mod_cats"></input><label for="scheduling-checks-mod_cats"> {{ program.getModeratorTitle }}s
can we capitalize the first letter of the moderator title in these final four checks as well?

2023-09-20 01:06 UTC, willgearty commented
Thanks for the great comments, @kkbrum! I believe I've addressed all of them. Teacher and moderator availability checks now skip the other availabilities, while the double-booked check now covers both.

2023-09-27 00:32 UTC, kkbrum approved these changes

2023-09-27 00:38 UTC, merged