Add reset and remove button for optional fruitsalad variables
learning-unlimited/ESP-Website pull request #3696
Opened 2023-11-08 02:59 UTC by willgearty

This adds the following functionality to the theme editor:

- Added a "Reset Color" button next to each color chooser

And when optional variables are included (I believe this is just for the fruitsalad theme atm):

- Added a "Remove Variable" button next to the new "Reset Color" buttons which removes the entire variable from the form
- Made it so you can't add a variable that already exists in the form

I've checked and the addition and removal of variables is saved whenever you press the "Test" submission button.

![image](https://github.com/learning-unlimited/ESP-Website/assets/7232514/a18f6a1c-292c-48a8-8e93-619b71d6f896)

Fixes #3674. Supersedes #3675.

2023-11-29 02:13 UTC, kkbrum requested changes
This is great! When I add optional accent variables, could the first color that shows up be the default color? I get black for all of them instead of the default. Also, if I reset the button or tab colors, I also get black. I'd rather it reset to the default, which I don't believe is black.

2023-11-29 20:45 UTC, willgearty commented
@kkbrum I'm not quite sure what you mean by the "default" color. Do you mean the first color in the palette (in which case the default for all of them would be the same)? Or do you mean the color that the variable is normally set to (in which case the default may be different for each variable)?

2023-12-08 01:06 UTC, kkbrum commented
I think it should start as the color that the variable is automatically set to if it is not included as an optional variable. So it's different for each one. Then you can see the current color when you add it as a variable so you know you're working on the right thing and have a good baseline for the color. And then can reset it to that as well.

2023-12-13 01:56 UTC, willgearty commented
OK, I've made it so that when you add a new variable, the initial color is the default color. And, whenever you reset one of these variables (plus the other variables, including the rounding_radius), it resets to whatever the default color/value is.

2023-12-13 02:23 UTC, kkbrum reviewed
Thanks! I like this a lot. I have two comments below, which you can address if you want to or if it seems easy, but I'm okay with approving the PR as it is.
1. It would be cool if when you have already added an optional variable, it no longer showed up in the dropdown list of variables that can be added.
2. The reset to default for the accent colors currently gives the right defaults if the fruitsalad tab colors have not been changed from their defaults. I think it would be slightly better if the reset to default for the accent gives the default "%" increase applied to the currently configured tab colors, which may be different than the default tab colors.

2023-12-20 02:02 UTC, willgearty commented
OK, the recent commit does #1 (great suggestion), but I don't think I'll implement #2 because I want the "Reset Color" buttons to all do the same thing (reset to the theme default).

2023-12-22 01:41 UTC, kkbrum approved these changes

2023-12-22 01:43 UTC, merged