Unsubscribe links and domain-only "From" email addresses
learning-unlimited/ESP-Website pull request #3721
Opened 2024-02-16 03:37 UTC by willgearty

This does the following:

- Can now generate unsubscribe links for users (including adding these to commpanel emails)
- Upon clicking these links, users can unsubscribe without logging in (within 7 days of being generated)
- Email clients can also use a "oneclick" version to instantly unsubscribe a user with a single POST
- The "From" email address for comm panel emails must now contain the LU domain or any LU subdomain (or a chapter-specific alias); there is a nice big red banner to announce this and there are frontend and backend checks to enforce this
- To help chapters, we now generate/use info@subdomain.learningu.org as an email redirect to their "default" email address; this is now automatically populated in the "From" field

Still to do:

- There are lots of emails that we send using the "director_email" email address; this probably needs to be changed to info@subdomain.learningu.org or something, but I'm still not sure how to best make this customizable for each program/chapter

Fixes #1719 and fixes #3709.

2024-02-23 22:23 UTC, willgearty commented
This is finally ready to be reviewed @kkbrum @milescalabresi!

2024-02-28 02:32 UTC, kkbrum requested changes
The migrations and such look good. The template tag unsubscribe link works well at least when the token is valid. For the other forms, I'll have to test a bit more on dev5 when we test the stable release. For now, just one minor request clarifying the username.

2024-02-28 02:32 UTC, kkbrum commented on esp/templates/users/unsubscribe.html
> +<p>We're sorry to see you go. If you are sure you would like to deactivate your account and unsubscribe from emails from {{ settings.INSTITUTION_NAME }} {{ settings.ORGANIZATION_SHORT_NAME }}, please
For the purpose where you are logged into the wrong account but the token is valid, I think we should clarify the "your account" bit here. I think putting the username is parentheses after the "your account" would be sufficient. It clarifies it on the success page, but that's after the fact...

2024-03-06 01:12 UTC, kkbrum approved these changes

2024-03-06 01:13 UTC, merged